my_site/BlogApp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ArticlesListView, ArticleCreateView, CreateAuthorView)


app_name = "BlogApp"

routers = DefaultRouter()
routers.register("articles", ArticlesListView)

# Обращение к ссылками на страницах всегда идет по имени - name
urlpatterns = [
    path("", ArticlesListView.as_view(), name="index"),
    path("new/", ArticleCreateView.as_view(), name="article-create"),
    path('create-author/', CreateAuthorView.as_view(), name='create_author'),
]

my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # Обязательно документация должна быть на 1 месте иначе доступ будет невозможен
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('rss/', include('rss_news.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
]
# Можно использовать только в основном файле urls.py в корне проекта
urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('articles/', include('BlogApp.urls')),
    
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include('debug_toolbar.urls')),
    )

my_site/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (get_cookie_view, set_cookie_view, AboutMeView,
                    RegisterView, UserListView, UserDetailView, UserUpdateAvatarView,
                    set_session_view, get_session_view, MyLogoutView,
                    FooBarView, update_profile, HelloView)


app_name = "myauth"
# Обращение к ссылками на страницах всегда идет по имени - name
urlpatterns = [
    # path("login/", login_view, name="login"),
    # LoginView ищет стандартную страницу аутентификации(registration.html) чтобы это изменить
    # добавим свою страницу
    path("login/", LoginView.as_view(
        template_name="myauth/login.html",
        redirect_authenticated_user=True
    ), name="login"),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("register/", RegisterView.as_view(), name="register"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path('about-me/update/', update_profile, name='profile_update'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/update-avatar/', UserUpdateAvatarView.as_view(), name='user_update_avatar'),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

my_site/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ShopIndexView, GroupsListView,
                    OrdersListView, OrderDetailView,
                    OrderCreateView, ProductCreateView,
                    ProductDetailsView, ProductsListView,
                    ProductUpdateView, ProductDeleteView,
                    OrderUpdateView, OrderDeleteView,
                    ProductsDataExportView, OrdersDataExportView,
                    ProductViewSet, OrdersViewSet, LatestProductFeed,
                    UserOrdersListView, UserOrdersDataExportView,
                    )
from django.views.decorators.cache import cache_page


app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrdersViewSet)

# Обращение к ссылками на страницах всегда идет по имени - name
urlpatterns = [
    # Добавим декоратор на класс ShopIndexView, чтобы кешировать класс
    path("", cache_page(60 * 3)(ShopIndexView.as_view()), name="index"),
    path("api/", include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/new/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive', ProductDeleteView.as_view(), name='product_delete'),
    path('products/latest/feed/', LatestProductFeed(), name='products-feed'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders-export'),
    path('order/new/', OrderCreateView.as_view(), name='create_order'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete', OrderDeleteView.as_view(), name='order_delete'),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name='user_orders'),
    path('users/<int:user_id>/orders/export/', UserOrdersDataExportView.as_view(), name='user-orders-export'),
    
]

my_site/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _, ngettext


# Можно сделать функцию, которая будет обрабатывать путь хранения и
# название сохраненного изображения продуктов и добавить ее в параметр 'upload_to'
def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return f"products/product_{instance.pk}/preview/{filename}"


class Product(models.Model):
    """
    Модель Product представляет товар для продажи в интернет-магазине
    Заказы тут :model:`shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"] # Сортирует в данном случае по имени и цене
        # db_table = "tech_products" # Позволяет обратиться к базе из которой брать модель
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
        # verbose_name_plural = "products" # Добавляет отображение модели во множественном числе
        
    name = models.CharField(max_length=32, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, default=None)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)
    
    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})
    
    @property
    def description_short(self) -> str:
        if len(self.description) < 48:
            return self.description
        return self.description[:48] + "..."
    
    def __str__(self) -> str:
        return f"Product(pk = {self.pk}), name = {self.name!r}"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)
    
    
class Order(models.Model):
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
    delivery_address = models.TextField(null=False, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts/')
    
    def get_absolute_url(self):
        return reverse("shopapp:order_details", kwargs={"pk": self.pk})

my_site/shopapp/forms.py
from django import forms
from django.core import validators
from .models import Product, Order
from django.forms import ModelForm
from django.contrib.auth.models import Group


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'description', 'discount', 'created_by', "preview" # Автоматическая генерация формы на основании данных в модели
    
    # Чтобы дать возможность загрузить сразу несколько изображений используем виджет
    # images = forms.FileField(
    #     widget=forms.ClearableFileInput(attrs={'multiple': True}),
    #     required=False)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = 'delivery_address', 'promocode', 'products', 'user'
        
        
class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = 'name',


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()
    

my_site/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <style>
        body {
            background-color: #f2f2f2;
        }
        .header {
            display: flex;
            justify-content: space-around;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
{% block header %}
<div class="header">
    <div><a href="{% url 'shopapp:products_list' %}">Products</a></div>
    <div><a href="{% url 'shopapp:groups_list' %}">Groups</a></div>
    <div><a href="{% url 'BlogApp:index' %}">Articles</a></div>
    <div><a href="{% url 'myauth:user-list' %}">Users</a></div>
    {% if user.is_authenticated %}

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.get_username }}
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'myauth:about-me' %}">Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'shopapp:user_orders' user_id=user.id %}">My orders</a></li>
              <li><a class="dropdown-item" href="{% url 'myauth:logout' %}">Logout</a></li>
          </ul>
        </div>
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" style="position: absolute;
                                                                border-radius: 50%;
                                                                height: 50px;
                                                                width: 50px;
                                                                margin-right: -90%;"/>
            {% endif %}
    {% else %}
        <div>
            <a href="{% url 'myauth:login' %}">Login</a><<<>>>
            <a href="{% url 'myauth:register' %}">Sign up</a>
        </div>
    {% endif %}
</div>
<hr>
{% endblock %}
{% block body %}

{% endblock %}
<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is: {{ current_weekday }}
</div>
</body>
</html>

my_site/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    New order
{% endblock %}

{% block body %}

    <h1> New order creation </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create order</button>
        </form>
    </div>
<div>
    <a href="{% url 'shopapp:products_list' %}"> >>> Back to products <<< </a>
</div>
<div>
    <a href="{% url 'shopapp:orders_list' %}"> >>> Back to orders <<< </a>
</div>


{% endblock %}

my_site/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    New product
{% endblock %}

{% block body %}

    <h1> New product creation </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create product</button>
        </form>
    </div>
<div>
    <a href="{% url 'shopapp:products_list' %}"> >>> Back to products <<< </a>
</div>
{% endblock %}

my_site/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}

    <h1> Groups:  </h1>
    <div> <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form></div>
    <div>
        {% if not groups %}
        <h3> Not yet groups </h3>
        {% else %}
        <ul>
            {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                <ul>
                    {% for permission in group.permissions.all %}
                    <li> {{ permission.name }}
                        (<code>{{ permission.codename }}</code>)
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

{% endblock %}

my_site/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.pk }}
{% endblock %}

{% block body %}
    <h1> Are you sure you want to delete {{ object.pk }}?</h1>
<hr>
<br>
<div>
    <a href="{% url 'shopapp:orders_list' %}"> >>> Back to orders <<< </a>
</div>
<br>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Delete</button>
    </form>
</div>
{% endblock %}

my_site/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }}
{% endblock %}

{% block body %}

    <h1> Order #{{ object.pk }} </h1>
    <div>
        <p>Ordered by: {% firstof object.user.first_name object.user.username %}</p>
        <p>Promocode: <code>{{ object.promocode }}</code></p>
        <p>Delivery address: {{ object.delivery_address }}</p>
        <div> Products in order:
            <ul>
                {% for product in object.products.all %}
                <li>{{ product.name }} for ${{ product.price }} </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div>
        <a href="{% url 'shopapp:order_update' pk=object.pk %}"> >>> Update order <<< </a>
    </div>
    <div>
        <a href="{% url 'shopapp:order_delete' pk=object.pk %}"> >>> Delete order <<< </a>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}"> >>> Back to orders <<< </a>
    </div>
{% endblock %}

my_site/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    New order
{% endblock %}

{% block body %}

    <h1> New order creation </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create order</button>
        </form>
    </div>
<div>
    <a href="{% url 'shopapp:orders_list' %}"> >>> Back to orders <<< </a>
</div>
{% endblock %}

my_site/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}
{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1> Orders </h1>
        {% if object_list %}
        {% cache 60 owner.pk %}
    <div>{% for order in object_list %}</div>
        <div>
            <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details of order {{ order.pk}}</a></p>
            <p>Ordered by: {% firstof order.user.first_name order.user.username %}</p>
            <p>Promocode: <code>{{ order.promocode }}</code></p>
            <p>Delivery address: {{ order.delivery_address }}</p>
            <div> Products in order:
                <ul>
                    {% for product in order.products.all %}
                    <li>{{ product.name }} for ${{ product.price }} </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endfor %}
        {% endcache %}
        {% else %}
    <h3>No orders yet...</h3>
        {% endif %}
    <div>
        <a href="{% url 'shopapp:create_order' %}"> >>> Create new order <<< </a>
    </div>
{% endblock %}

my_site/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update order {{ product.pk }}
{% endblock %}

{% block body %}

    <h1> Update order </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update order</button>
        </form>
    </div>
<div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}"> >>> Return to order <<< </a>
</div>
<div>
    <a href="{% url 'shopapp:orders_list' %}"> >>> Back to orders list <<< </a>
</div>
{% endblock %}

my_site/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}

    <h1> Orders </h1>
        {% if orders %}
    <div>{% for order in orders %}</div>
        <div>
            <p>Ordered by: {% firstof order.user.first_name order.user.username %}</p>
            <p>Promocode: <code>{{ order.promocode }}</code></p>
            <p>Delivery address: {{ order.delivery_address }}</p>
            <div> Products in order:
                <ul>
                    {% for product in order.products.all %}
                    <li>{{ product.name }} for ${{ product.price }} </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endfor %}
        {% else %}
    <h3>No orders yet...</h3>
        {% endif %}
    <div>
        <a href="{% url 'shopapp:create_order' %}"> >>> Create new order <<< </a>
    </div>
{% endblock %}

my_site/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1><strong>{{ product.name }}</strong></h1>
    <div>
            <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
            <div>{% translate 'Price' %}: <em>{{ product.price }}</em></div>
            <div>{% translate 'Discount' %}: <em>{{ product.discount }}</em></div>
            <div>{% translate 'Created by' %}: <em>{{ product.created_by }}</em></div>
            <div>{% translate 'Archived' %}: <em>{{ product.archived }}</em></div>
        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.previe.name }}" style="width: 25%">
        {% endif %}
        <h3> {% translate 'Images' %}: </h3>
        <div>
            {% blocktranslate count images_count=product.images.all|length %}
                <div>
                    There is only one image available
                    {% plural %}
                    There are {{ images_count }} images available
                </div>
            {% endblocktranslate %}
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}" style="width: 25%">
                    <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>{% translate 'No images' %}...</div>
            {% endfor %}
        </div>

    </div>
    <div>
        {% if perms.shopapp.change_product and owner == user %}
            <a href="{% url 'shopapp:product_update' pk=product.pk %}"> >>> {% translate 'Update product' %} <<< </a>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}"> >>> {% translate 'Archive product' %} <<< </a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}"> >>> {% translate 'Back to products' %} <<< </a>
    </div>

{% endblock %}

my_site/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1> Are you sure you want to move to archive {{ object.name }}?</h1>
<hr>
<br>
<div>
    <a href="{% url 'shopapp:products_list' %}"> >>> Back to products <<< </a>
</div>
<br>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">To Archive</button>
    </form>
</div>
{% endblock %}

my_site/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    New product
{% endblock %}

{% block body %}

    <h1> New product creation </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create product</button>
        </form>
    </div>
<div>
    <a href="{% url 'shopapp:products_list' %}"> >>> Back to products <<< </a>
</div>
{% endblock %}

my_site/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}
{% block title %}
    Shop index
{% endblock %}

{% block body %}

    <h1> Hello Shop App </h1>
    <div>
        <ul>
            {% for name, price in products %}
                <li>Product name: {{ name }}
                    Product price: {{ price}}
                </li>
            {% empty %}
            No products yet...
            {% endfor %}
        </ul>
    </div>
    <div>
        <strong>
<!--            Если окончание должно быть просто множественное число используем{{ items|pluralize }}-->
<!--            Будет добавлено 's' в конце. А если нет, то добавляем свое окончание как в примере-->
<!--            А если слово полностью меняет окончание, то надо указать варианты через запятую-->
<!--            item{{ cherr|pluralize:"y, ies" }} где 'y' - для удинственного числа, а 'ies' для множественного-->
            You have {{ items }} item{{ items|pluralize:"es" }}
        </strong>
    </div>
    <div>
        Time running: {{ time_running }}
    </div>
{% cache 100 lorem products %}
<!-- Обязательно указывает период кеширования и название ключа (отдельный ключ, он не связан с тегом lorem)-->
<!-- переменная lorem products указывает, что для этого блока products будет один кэш, а для другого блока с другим products - другой-->
    <div>
        {% lorem 3 p random %}
    </div>
{% endcache %}

{% endblock %}