my_site/BlogApp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ArticlesListView, ArticleCreateView, CreateAuthorView)


app_name = "BlogApp"

routers = DefaultRouter()
routers.register("articles", ArticlesListView)

# Обращение к ссылками на страницах всегда идет по имени - name
urlpatterns = [
    path("", ArticlesListView.as_view(), name="index"),
    path("new/", ArticleCreateView.as_view(), name="article-create"),
    path('create-author/', CreateAuthorView.as_view(), name='create_author'),
]

my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # Обязательно документация должна быть на 1 месте иначе доступ будет невозможен
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('rss/', include('rss_news.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
]
# Можно использовать только в основном файле urls.py в корне проекта
urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('articles/', include('BlogApp.urls')),
    
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include('debug_toolbar.urls')),
    )

my_site/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (get_cookie_view, set_cookie_view, AboutMeView,
                    RegisterView, UserListView, UserDetailView, UserUpdateAvatarView,
                    set_session_view, get_session_view, MyLogoutView,
                    FooBarView, update_profile, HelloView)


app_name = "myauth"
# Обращение к ссылками на страницах всегда идет по имени - name
urlpatterns = [
    # path("login/", login_view, name="login"),
    # LoginView ищет стандартную страницу аутентификации(registration.html) чтобы это изменить
    # добавим свою страницу
    path("login/", LoginView.as_view(
        template_name="myauth/login.html",
        redirect_authenticated_user=True
    ), name="login"),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("register/", RegisterView.as_view(), name="register"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path('about-me/update/', update_profile, name='profile_update'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/update-avatar/', UserUpdateAvatarView.as_view(), name='user_update_avatar'),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

my_site/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ShopIndexView, GroupsListView,
                    OrdersListView, OrderDetailView,
                    OrderCreateView, ProductCreateView,
                    ProductDetailsView, ProductsListView,
                    ProductUpdateView, ProductDeleteView,
                    OrderUpdateView, OrderDeleteView,
                    ProductsDataExportView, OrdersDataExportView,
                    ProductViewSet, OrdersViewSet, LatestProductFeed,
                    UserOrdersListView, UserOrdersDataExportView,
                    )
from django.views.decorators.cache import cache_page


app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrdersViewSet)

# Обращение к ссылками на страницах всегда идет по имени - name
urlpatterns = [
    # Добавим декоратор на класс ShopIndexView, чтобы кешировать класс
    path("", cache_page(60 * 3)(ShopIndexView.as_view()), name="index"),
    path("api/", include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/new/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive', ProductDeleteView.as_view(), name='product_delete'),
    path('products/latest/feed/', LatestProductFeed(), name='products-feed'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders-export'),
    path('order/new/', OrderCreateView.as_view(), name='create_order'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete', OrderDeleteView.as_view(), name='order_delete'),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name='user_orders'),
    path('users/<int:user_id>/orders/export/', UserOrdersDataExportView.as_view(), name='user-orders-export'),
    
]

my_site/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_preview_directory_path(instance: "User", filename: str) -> str:
    return f"myauth/my_info/preview/{filename}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_preview_directory_path)

my_site/myauth/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'agreement_accepted', 'avatar')
        

my_site/myauth/views.py
from random import random
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView
from django.utils.decorators import method_decorator
# from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _, ngettext
# Теперь к функции gettext можно обращаться через _. Позволяет переводить объекты на
# верхнем уровне, то есть там, где еще не известна локализация пользователя
# Ленивый перевод это подготовка к переводу
# ngettext - используется для плюрализации(изменению окончаний названий в соответствии с количеством)
# 1 товар, 10 товаров и тд

from .forms import ProfileForm
from .models import Profile


# Ленивые функции позволяют возвращать объекты не в момент вызова функции, а в
# момент обращения к полученному объекту
# Для создания переводов выполним в терминале python manage.py makemessages -l ru
# А после этого для компиляции всех переведенных слов
class HelloView(View):
    welcome_message = _("Hello world")
    def get(self, request: HttpRequest) -> HttpResponse:
        items_string = request.GET.get('items') or 0
        items = int(items_string)
        products_line = ngettext(
            'one product',
            '{count} products',
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(f"<h1>{self.welcome_message}</h1>"
                            f"\n<h2>{products_line}</h2>")
        
class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"
    

class RegisterView(CreateView):
    form_class = UserCreationForm# Необходимо указывать форму, на основе которой будет создана новая сущность
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")
    
    # Чтобы произвести аутентификацию пользователя, надо доработать класс
    # переопределив метод
    def form_valid(self, form):
        response = super().form_valid(form)
        # Лучше связать создание профиля при создании нового пользователя
        Profile.objects.create(user=self.object) # self.object - сохраняется сразу по form_valid()
        # Данные о пользователе и пароле надо вытащить из формы
        
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password)
        login(self.request, user=user)
        # Profile.objects.create(user=user) # Так не желательно,
        # потому что так мы завязываем эту логику с аутентификацией пользователя
        return response
    
    
def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/shopapp/products-list')
        return render(request, '/shopapp/products-list')
    
    username = request.POST['username']
    password = request.POST['password']
    
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/shopapp/products-list')
    return render(request, "myauth/login.html", {'Error': 'Invalid credentials'})


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse("myauth:login"))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


@cache_page(60 * 2) # Добавим кеширование странцы на 2 мин
@user_passes_test(lambda u: u.is_superuser) # Может отправить в бесконечный цикл
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default_value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spamm-eggs'
    return HttpResponse("Session set")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default_value')
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})
    

def update_profile(request):
    profile = request.user.profile
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return render(request, 'myauth/about-me.html')
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'myauth/profile_update.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class UserListView(ListView):
    model = Profile
    template_name = 'myauth/user-list.html'
    context_object_name = 'profiles'
    
    def user_list_view(request):
        users = User.objects.all()
        return render(request, 'user-list.html', {'users': users})
    
    def get_queryset(self):
        return super().get_queryset()


@method_decorator(login_required, name='dispatch')
class UserDetailView(DetailView):
    model = Profile
    # queryset = User.objects.prefetch_related("profile")
    template_name = 'myauth/user_detail.html'
    context_object_name = 'user'
    
    def get_queryset(self):
        # Вы вызываете prefetch_related, чтобы сократить количество запросов к базе данных
        return User.objects.prefetch_related("profile")
    
    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        user = context['user']  # 'user' вместо 'profile', чтобы избежать путаницы
        context['can_update_avatar'] = self.request.user.is_staff or self.request.user == user
        return context


# @method_decorator(staff_member_required, name='dispatch')
class UserUpdateAvatarView(UserPassesTestMixin, UpdateView):
    model = Profile
    template_name = 'myauth/user_update_avatar.html'
    fields = ['avatar']
    context_object_name = 'profile'
    
    def test_func(self):
        profile = get_object_or_404(Profile, pk=self.kwargs.get('pk'))
        return self.request.user == profile.user or self.request.user.is_staff
    
    def get_success_url(self):
        # возвращает пользователя на страницу его профиля после изменения аватара
        return reverse('profile_detail', kwargs={'pk': self.request.user.profile.pk})
    
    def get_queryset(self):
        # Здесь можно добавить более специфичную логику, если необходимо
        return Profile.objects.select_related('user').filter(user=self.request.user)

my_site/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}
{% block title %}
    About me
{% endblock %}

{% block body %}
  <h1>User info</h1>
  {% if user.is_authenticated %}
<!-- Добавим уникальный кэш для каждого пользователя-->
    {% cache 300 userinfo user.username %}
     <h2>{{ user.username }}</h2>
  <h3>Details</h3>
    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="Avatar" style="max-width: 200px"/>
        <p><a href="{% url 'myauth:profile_update' %}"> >>> Change avatar <<< </a></p>
    {% else %}
      <p>No avatar yet</p>
      <a href="{% url 'myauth:profile_update' %}"> >>> Update profile <<< </a>
    {% endif %}
    <p>Username: {{ user.username }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Bio: {{ user.profile.bio }}</p>
    {% endcache %}
  {% else %}
    <p>You are not logged in</p>
  {% endif %}
{% endblock %}

my_site/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <style>
        body {
            background-color: #f2f2f2;
        }
        .header {
            display: flex;
            justify-content: space-around;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
{% block header %}
<div class="header">
    <div><a href="{% url 'shopapp:products_list' %}">Products</a></div>
    <div><a href="{% url 'shopapp:groups_list' %}">Groups</a></div>
    <div><a href="{% url 'BlogApp:index' %}">Articles</a></div>
    <div><a href="{% url 'myauth:user-list' %}">Users</a></div>
    {% if user.is_authenticated %}

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.get_username }}
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'myauth:about-me' %}">Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'shopapp:user_orders' user_id=user.id %}">My orders</a></li>
              <li><a class="dropdown-item" href="{% url 'myauth:logout' %}">Logout</a></li>
          </ul>
        </div>
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" style="position: absolute;
                                                                border-radius: 50%;
                                                                height: 50px;
                                                                width: 50px;
                                                                margin-right: -90%;"/>
            {% endif %}
    {% else %}
        <div>
            <a href="{% url 'myauth:login' %}">Login</a><<<>>>
            <a href="{% url 'myauth:register' %}">Sign up</a>
        </div>
    {% endif %}
</div>
<hr>
{% endblock %}
{% block body %}

{% endblock %}
<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is: {{ current_weekday }}
</div>
</body>
</html>

my_site/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

my_site/myauth/templates/myauth/profile_update.html
{% extends 'myauth/base.html' %}

{% block title %}
    Profile update
{% endblock %}

{% block body %}

    <h1> Profile update </h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update profile</button>
        </form>
    </div>
<div>
    <a href="{% url 'myauth:about-me' %}"> >>> Back to profile <<< </a>
</div>
{% endblock %}

my_site/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="register">
    </form>
{% endblock %}

my_site/myauth/templates/myauth/user-list.html
{% extends 'myauth/base.html' %}

{% block body %}
  <h1>User List</h1>
  <ul>
    {% for profile in profiles %}
      <li>
        <a href="{% url 'myauth:user_detail' pk=profile.user.pk %}">{{ profile.user.username }}</a>
        / User ID: {{ profile.user.id }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

my_site/myauth/templates/myauth/user_detail.html
{% extends 'myauth/base.html' %}

{% block body %}
  <h1>User Detail</h1>
  <h2>{{ user.profile.username }}</h2>
  <img src="{{ user.profile.avatar.url }}" alt="Avatar" style="max-width: 200px">
  
  {% if can_update_avatar %}
    <a href="{% url 'myauth:user_update_avatar' user.profile.pk %}">Update Avatar</a>
  {% endif %}
{% endblock %}

my_site/myauth/templates/myauth/user_update_avatar.html
{% extends 'myauth/base.html' %}

{% block body %}
  <h1>Update Avatar</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}